name = "lms-guide-leads"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "LEADS"
id = "113dd2a3279a4d3e96f538fecc8b0db3"

[vars]
GOOGLE_SHEET_ID = "1OjoWG_KuhnlP9EIb-tVzPNPw3tIf8dXTS_-OcH4kJLQ"
